name: "running unit test,build docker"
on:
  push:
    branches:
      - "testing_lite"
jobs:
  unit-test:
    name: "unit  test"
    runs-on: ubuntu-latest
    steps:
      - name: Setup github action (CI)
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Running unit test
        run: go test ./... -cover